In [3]:
pip install pandas

Requirement already satisfied: pandas in c:\users\acer\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\acer\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

## Grouping and Sorting

In [1]:
import pandas as pd

In [2]:
Matches = pd.read_csv("matches.csv")

In [3]:
Matches.groupby('result_margin').result_margin.count()

result_margin
1.0       18
2.0       21
3.0       39
4.0       74
5.0      109
        ...
130.0      1
138.0      1
140.0      1
144.0      1
146.0      1
Name: result_margin, Length: 98, dtype: int64

In [7]:
Matches.groupby('result_margin').target_runs.min()

result_margin
1.0      121.0
2.0      130.0
3.0       53.0
4.0      102.0
5.0       98.0
         ...
130.0    264.0
138.0    227.0
140.0    223.0
144.0    249.0
146.0    213.0
Name: target_runs, Length: 98, dtype: float64

In [9]:
Matches.groupby('venue').apply(lambda df: df.team1.iloc[0])

C:\Users\Dolli\AppData\Local\Temp\ipykernel_2464\2053192628.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  Matches.groupby('venue').apply(lambda df: df.team1.iloc[0])

venue
Arun Jaitley Stadium                                                                 Kings XI Punjab
Arun Jaitley Stadium, Delhi                                                      Sunrisers Hyderabad
Barabati Stadium                                                                     Deccan Chargers
Barsapara Cricket Stadium, Guwahati                                                     Punjab Kings
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow           Lucknow Super Giants
Brabourne Stadium                                                                     Mumbai Indians
Brabourne Stadium, Mumbai                                                        Chennai Super Kings
Buffalo Park                                                                   Kolkata Knight Riders
De Beers Diamond Oval                                                                Deccan Chargers
Dr DY Patil Sports Academy                                                            Mumbai Indians
Dr DY Patil Sports Academy, Mumbai                                       Royal Challengers Bangalore
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                                  Deccan Chargers
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam                    Delhi Capitals
Dubai International Cricket Stadium                                      Royal Challengers Bangalore
Eden Gardens                                                                   Kolkata Knight Riders
Eden Gardens, Kolkata                                                               Rajasthan Royals
Feroz Shah Kotla                                                                    Delhi Daredevils
Green Park                                                                             Gujarat Lions
Himachal Pradesh Cricket Association Stadium                                         Kings XI Punjab
Himachal Pradesh Cricket Association Stadium, Dharamsala                              Delhi Capitals
Holkar Cricket Stadium                                                          Kochi Tuskers Kerala
JSCA International Stadium Complex                                             Kolkata Knight Riders
Kingsmead                                                                            Kings XI Punjab
M Chinnaswamy Stadium                                                    Royal Challengers Bangalore
M Chinnaswamy Stadium, Bengaluru                                                      Mumbai Indians
M.Chinnaswamy Stadium                                                    Royal Challengers Bangalore
MA Chidambaram Stadium                                                         Kolkata Knight Riders
MA Chidambaram Stadium, Chepauk                                                  Chennai Super Kings
MA Chidambaram Stadium, Chepauk, Chennai                                              Mumbai Indians
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur                    Delhi Capitals
Maharashtra Cricket Association Stadium                                                Pune Warriors
Maharashtra Cricket Association Stadium, Pune                                       Rajasthan Royals
Narendra Modi Stadium, Ahmedabad                                                        Punjab Kings
Nehru Stadium                                                                   Kochi Tuskers Kerala
New Wanderers Stadium                                                            Chennai Super Kings
Newlands                                                                         Chennai Super Kings
OUTsurance Oval                                                                     Delhi Daredevils
Punjab Cricket Association IS Bindra Stadium                                        Delhi Daredevils
Punjab Cricket Association IS Bindra Stadium, Mohali                                 Kings XI Punjab
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh                        Punjab Kings
Punjab Cricket Association Stadium, Mohali                                           Kings XI Punjab
Rajiv Gandhi International Stadium                                                  Rajasthan Royals
Rajiv Gandhi International Stadium, Uppal                                            Deccan Chargers
Rajiv Gandhi International Stadium, Uppal, Hyderabad                                Rajasthan Royals
Sardar Patel Stadium, Motera                                                        Rajasthan Royals
Saurashtra Cricket Association Stadium                                                 Gujarat Lions
Sawai Mansingh Stadium                                                              Rajasthan Royals
Sawai Mansingh Stadium, Jaipur                                                  Lucknow Super Giants
Shaheed Veer Narayan Singh International Stadium                                    Delhi Daredevils
Sharjah Cricket Stadium                                                             Delhi Daredevils
Sheikh Zayed Stadium                                                                  Mumbai Indians
St George's Park                                                         Royal Challengers Bangalore
Subrata Roy Sahara Stadium                                                             Pune Warriors
SuperSport Park                                                                     Delhi Daredevils
Vidarbha Cricket Association Stadium, Jamtha                                         Deccan Chargers
Wankhede Stadium                                                                      Mumbai Indians
Wankhede Stadium, Mumbai                                                         Chennai Super Kings
Zayed Cricket Stadium, Abu Dhabi                                         Royal Challengers Bangalore
dtype: object

In [11]:
Matches.groupby(['city', 'season']).apply(lambda df: df.loc[df.result_margin.idxmax()])

C:\Users\Dolli\AppData\Local\Temp\ipykernel_2464\235422357.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  Matches.groupby(['city', 'season']).apply(lambda df: df.loc[df.result_margin.idxmax()])

                            id   season           city        date  \
city          season
Abu Dhabi     2014      729293     2014      Abu Dhabi  2014-04-21
              2020/21  1216497  2020/21      Abu Dhabi  2020-10-24
              2021     1254088     2021      Abu Dhabi  2021-10-08
Ahmedabad     2009/10   419118  2009/10      Ahmedabad  2010-03-20
              2014      734011     2014      Ahmedabad  2014-05-15
...                        ...      ...            ...         ...
Visakhapatnam 2012      548311     2012  Visakhapatnam  2012-04-07
              2015      829743     2015  Visakhapatnam  2015-04-22
              2016      980973     2016  Visakhapatnam  2016-05-08
              2019     1181767     2019  Visakhapatnam  2019-05-10
              2024     1422134     2024  Visakhapatnam  2024-04-03

                        match_type  player_of_match  \
city          season
Abu Dhabi     2014          League         SK Raina
              2020/21       League         CV Varun
              2021          League     Ishan Kishan
Ahmedabad     2009/10       League  AA Jhunjhunwala
              2014          League        AM Rahane
...                            ...              ...
Visakhapatnam 2012          League        RA Jadeja
              2015          League        DA Warner
              2016          League          A Nehra
              2019     Qualifier 2     F du Plessis
              2024          League        SP Narine

                                                                   venue  \
city          season
Abu Dhabi     2014                                  Sheikh Zayed Stadium
              2020/21                               Sheikh Zayed Stadium
              2021                      Zayed Cricket Stadium, Abu Dhabi
Ahmedabad     2009/10                       Sardar Patel Stadium, Motera
              2014                          Sardar Patel Stadium, Motera
...                                                                  ...
Visakhapatnam 2012     Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
              2015     Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
              2016     Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
              2019     Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
              2024     Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...

                                       team1                  team2  \
city          season
Abu Dhabi     2014       Chennai Super Kings       Delhi Daredevils
              2020/21  Kolkata Knight Riders         Delhi Capitals
              2021            Mumbai Indians    Sunrisers Hyderabad
Ahmedabad     2009/10       Rajasthan Royals  Kolkata Knight Riders
              2014          Rajasthan Royals       Delhi Daredevils
...                                      ...                    ...
Visakhapatnam 2012           Deccan Chargers    Chennai Super Kings
              2015       Sunrisers Hyderabad  Kolkata Knight Riders
              2016            Mumbai Indians    Sunrisers Hyderabad
              2019            Delhi Capitals    Chennai Super Kings
              2024     Kolkata Knight Riders         Delhi Capitals

                                 toss_winner toss_decision  \
city          season
Abu Dhabi     2014       Chennai Super Kings           bat
              2020/21         Delhi Capitals         field
              2021            Mumbai Indians           bat
Ahmedabad     2009/10       Rajasthan Royals           bat
              2014          Delhi Daredevils         field
...                                      ...           ...
Visakhapatnam 2012           Deccan Chargers         field
              2015     Kolkata Knight Riders         field
              2016            Mumbai Indians         field
              2019       Chennai Super Kings         field
              2024     Kolkata Knight Riders           bat

                                      winner   result  result_margin  \
city          season
Abu Dhabi     2014       Chennai Super Kings     runs           93.0
              2020/21  Kolkata Knight Riders     runs           59.0
              2021            Mumbai Indians     runs           42.0
Ahmedabad     2009/10       Rajasthan Royals     runs           34.0
              2014          Rajasthan Royals     runs           62.0
...                                      ...      ...            ...
Visakhapatnam 2012       Chennai Super Kings     runs           74.0
              2015       Sunrisers Hyderabad     runs           16.0
              2016       Sunrisers Hyderabad     runs           85.0
              2019       Chennai Super Kings  wickets            6.0
              2024     Kolkata Knight Riders     runs          106.0

                       target_runs  target_overs super_over method  \
city          season
Abu Dhabi     2014           178.0          20.0          N    NaN
              2020/21        195.0          20.0          N    NaN
              2021           236.0          20.0          N    NaN
Ahmedabad     2009/10        169.0          20.0          N    NaN
              2014           202.0          20.0          N    NaN
...                            ...           ...        ...    ...
Visakhapatnam 2012           194.0          20.0          N    NaN
              2015           118.0          12.0          N    D/L
              2016           178.0          20.0          N    NaN
              2019           148.0          20.0          N    NaN
              2024           273.0          20.0          N    NaN

                              umpire1          umpire2
city          season
Abu Dhabi     2014     RK Illingworth    C Shamshuddin
              2020/21     CB Gaffaney        PG Pathak
              2021       Tapan Sharma        VK Sharma
Ahmedabad     2009/10     RE Koertzen        RB Tiffin
              2014             S Ravi        RJ Tucker
...                               ...              ...
Visakhapatnam 2012          JD Cloete  HDPK Dharmasena
              2015     RK Illingworth      VA Kulkarni
              2016             S Ravi    C Shamshuddin
              2019       BNJ Oxenford           S Ravi
              2024            A Totre        UV Gandhe

[163 rows x 20 columns]

In [13]:
Matches.groupby('team1').target_runs.agg([len, min, max])

C:\Users\Dolli\AppData\Local\Temp\ipykernel_2464\4011699821.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  Matches.groupby('team1').target_runs.agg([len, min, max])
C:\Users\Dolli\AppData\Local\Temp\ipykernel_2464\4011699821.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  Matches.groupby('team1').target_runs.agg([len, min, max])

                             len    min    max
team1
Chennai Super Kings          128   98.0  247.0
Deccan Chargers               39  102.0  215.0
Delhi Capitals                41  111.0  258.0
Delhi Daredevils              85   43.0  232.0
Gujarat Lions                 16  125.0  214.0
Gujarat Titans                21   90.0  234.0
Kings XI Punjab               92   68.0  241.0
Kochi Tuskers Kerala           7   98.0  179.0
Kolkata Knight Riders        121   52.0  273.0
Lucknow Super Giants          23  154.0  258.0
Mumbai Indians               123   68.0  236.0
Pune Warriors                 23  100.0  188.0
Punjab Kings                  31  107.0  222.0
Rajasthan Royals             101   71.0  223.0
Rising Pune Supergiant         7   74.0  206.0
Rising Pune Supergiants        7   58.0  196.0
Royal Challengers Bangalore  135   63.0  264.0
Royal Challengers Bengaluru    9  173.0  242.0
Sunrisers Hyderabad           86   48.0  288.0

## Multi-indexes

In [16]:
teams_venues_reviewed = Matches.groupby(['team1', 'venue']).winner.agg([len])
teams_venues_reviewed

                                                                        len
team1               venue
Chennai Super Kings Arun Jaitley Stadium, Delhi                           2
                    Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cr...    1
                    Brabourne Stadium                                     1
                    Brabourne Stadium, Mumbai                             3
                    Buffalo Park                                          1
...                                                                     ...
Sunrisers Hyderabad Sharjah Cricket Stadium                               2
                    Sheikh Zayed Stadium                                  3
                    Wankhede Stadium                                      3
                    Wankhede Stadium, Mumbai                              5
                    Zayed Cricket Stadium, Abu Dhabi                      1

[288 rows x 1 columns]

In [18]:
mi = teams_venues_reviewed.index
type(mi)

pandas.core.indexes.multi.MultiIndex

In [20]:
teams_venues_reviewed_reset = teams_venues_reviewed.reset_index()
teams_venues_reviewed_reset

,team1,venue,len
0,Chennai Super Kings,"Arun Jaitley Stadium, Delhi",2
1,Chennai Super Kings,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,1
2,Chennai Super Kings,Brabourne Stadium,1
3,Chennai Super Kings,"Brabourne Stadium, Mumbai",3
4,Chennai Super Kings,Buffalo Park,1
...,...,...,...
283,Sunrisers Hyderabad,Sharjah Cricket Stadium,2
284,Sunrisers Hyderabad,Sheikh Zayed Stadium,3
285,Sunrisers Hyderabad,Wankhede Stadium,3
286,Sunrisers Hyderabad,"Wankhede Stadium, Mumbai",5
287,Sunrisers Hyderabad,"Zayed Cricket Stadium, Abu Dhabi",1

## Sorting

In [23]:
# Group by 'team1' and 'venue', and get the count of 'winner'
teams_venues_reviewed = Matches.groupby(['team1', 'venue']).winner.agg([len])

# Reset the index
teams_venues_reviewed = teams_venues_reviewed.reset_index()
teams_venues_reviewed

,team1,venue,len
0,Chennai Super Kings,"Arun Jaitley Stadium, Delhi",2
1,Chennai Super Kings,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,1
2,Chennai Super Kings,Brabourne Stadium,1
3,Chennai Super Kings,"Brabourne Stadium, Mumbai",3
4,Chennai Super Kings,Buffalo Park,1
...,...,...,...
283,Sunrisers Hyderabad,Sharjah Cricket Stadium,2
284,Sunrisers Hyderabad,Sheikh Zayed Stadium,3
285,Sunrisers Hyderabad,Wankhede Stadium,3
286,Sunrisers Hyderabad,"Wankhede Stadium, Mumbai",5
287,Sunrisers Hyderabad,"Zayed Cricket Stadium, Abu Dhabi",1

In [25]:
teams_venues_reviewed.sort_values(by='len')

                           team1                             venue  len
287          Sunrisers Hyderabad  Zayed Cricket Stadium, Abu Dhabi    1
200             Rajasthan Royals              Arun Jaitley Stadium    1
199                 Punjab Kings  Zayed Cricket Stadium, Abu Dhabi    1
197                 Punjab Kings           Sharjah Cricket Stadium    1
105              Kings XI Punjab            Sawai Mansingh Stadium    1
..                           ...                               ...  ...
18           Chennai Super Kings   MA Chidambaram Stadium, Chepauk   45
68              Delhi Daredevils                  Feroz Shah Kotla   56
235  Royal Challengers Bangalore             M Chinnaswamy Stadium   60
178               Mumbai Indians                  Wankhede Stadium   61
122        Kolkata Knight Riders                      Eden Gardens   66

[288 rows x 3 columns]

In [27]:
teams_venues_reviewed.sort_values(by='len', ascending=False)

,team1,venue,len
122,Kolkata Knight Riders,Eden Gardens,66
178,Mumbai Indians,Wankhede Stadium,61
235,Royal Challengers Bangalore,M Chinnaswamy Stadium,60
68,Delhi Daredevils,Feroz Shah Kotla,56
18,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",45
...,...,...,...
134,Kolkata Knight Riders,Newlands,1
135,Kolkata Knight Riders,Rajiv Gandhi International Stadium,1
136,Kolkata Knight Riders,"Rajiv Gandhi International Stadium, Uppal, Hyd...",1
139,Kolkata Knight Riders,St George's Park,1
287,Sunrisers Hyderabad,"Zayed Cricket Stadium, Abu Dhabi",1

In [29]:
teams_venues_reviewed.sort_index()

,team1,venue,len
0,Chennai Super Kings,"Arun Jaitley Stadium, Delhi",2
1,Chennai Super Kings,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,1
2,Chennai Super Kings,Brabourne Stadium,1
3,Chennai Super Kings,"Brabourne Stadium, Mumbai",3
4,Chennai Super Kings,Buffalo Park,1
...,...,...,...
283,Sunrisers Hyderabad,Sharjah Cricket Stadium,2
284,Sunrisers Hyderabad,Sheikh Zayed Stadium,3
285,Sunrisers Hyderabad,Wankhede Stadium,3
286,Sunrisers Hyderabad,"Wankhede Stadium, Mumbai",5
287,Sunrisers Hyderabad,"Zayed Cricket Stadium, Abu Dhabi",1

In [31]:
teams_venues_reviewed.sort_values(by=['team1', 'len'])

,team1,venue,len
1,Chennai Super Kings,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,1
2,Chennai Super Kings,Brabourne Stadium,1
4,Chennai Super Kings,Buffalo Park,1
5,Chennai Super Kings,De Beers Diamond Oval,1
10,Chennai Super Kings,"Eden Gardens, Kolkata",1
...,...,...,...
281,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal, Hyd...",4
279,Sunrisers Hyderabad,Rajiv Gandhi International Stadium,5
286,Sunrisers Hyderabad,"Wankhede Stadium, Mumbai",5
266,Sunrisers Hyderabad,Dubai International Cricket Stadium,7
280,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",30