In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('deliveries dataset if.csv')

In [5]:
df1 = pd.read_csv('matches data set if.csv')

In [7]:
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [9]:
#calculate the mean, median, and mode for runs

from scipy import stats

# Calculate the mean
mean_runs = df['total_runs'].mean()
print(f"Mean runs: {mean_runs}")

# Calculate the median
median_runs = df['total_runs'].median()
print(f"Median runs: {median_runs}")

# Calculate the mode
mode_runs = stats.mode(df['total_runs'])
print(f"Mode runs: {mode_runs}")

Mean runs: 1.3328069906484745
Median runs: 1.0
Mode runs: ModeResult(mode=1, count=108440)

In [11]:
#calculate the mean, median, and mode for wickets

from scipy import stats

# Calculate the mean
mean_wickets = df['is_wicket'].mean()
print(f"Mean wickets: {mean_wickets}")

# Calculate the median
median_wickets = df['is_wicket'].median()
print(f"Median wickets: {median_wickets}")

# Calculate the mode
mode_wickets = stats.mode(df['is_wicket'])
print(f"Mode wickets: {mode_wickets}")

Mean wickets: 0.049632071132914304
Median wickets: 0.0
Mode wickets: ModeResult(mode=0, count=247970)

In [15]:
# Calculate the mean
mean_runs = df['total_runs'].mean()
print(f"Mean runs: {mean_runs}")

# Calculate the median
median_runs = df['total_runs'].median()
print(f"Median runs: {median_runs}")

# Calculate the mode
mode_runs = stats.mode(df['total_runs'])
print(f"Mode runs: {mode_runs}")
#calculate the mean, median, and mode for wickets


# Calculate the mean
mean_wickets = df['is_wicket'].mean()
print(f"Mean wickets: {mean_wickets}")

# Calculate the median
median_wickets = df['is_wicket'].median()
print(f"Median wickets: {median_wickets}")

# Calculate the mode
mode_wickets = stats.mode(df['is_wicket'])
print(f"Mode wickets: {mode_wickets}")

# Calculate strike rate for each batter
batter_strike_rates = df.groupby('batsman').apply(lambda x: (x['total_runs'].sum() / x['ball'].count()) * 100)
print(batter_strike_rates)

# Add the strike rate as a new column to the DataFrame (optional)
df['Normalized Strike Rate'] = df.groupby('batsman')['total_runs'].transform(lambda x: (x.sum() / df.groupby('batsman')['ball'].count()[x.name]) * 100)

Mean runs: 1.3328069906484745
Median runs: 1.0
Mode runs: ModeResult(mode=1, count=108440)
Mean wickets: 0.049632071132914304
Median wickets: 0.0
Mode wickets: ModeResult(mode=0, count=247970)

KeyError: 'batsman'