## **DATA ANALYSIS**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
deliveries_data = pd.read_csv("/content/deliveries.csv")
matches_data=pd.read_csv("/content/matches.csv")
deliveries_data

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [ ]:
deliveries_data.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [ ]:
deliveries_data.tail()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [ ]:
deliveries_data.shape

(260920, 17)

In [ ]:
deliveries_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

In [ ]:
deliveries_data.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [ ]:
deliveries_data.describe()

,match_id,inning,over,ball,batsman_runs,extra_runs,total_runs,is_wicket
count,2.609200e+05,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000
mean,9.070665e+05,1.483531,9.197677,3.624486,1.265001,0.067806,1.332807,0.049632
std,3.679913e+05,0.502643,5.683484,1.814920,1.639298,0.343265,1.626416,0.217184
min,3.359820e+05,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,5.483340e+05,1.000000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000
50%,9.809670e+05,1.000000,9.000000,4.000000,1.000000,0.000000,1.000000,0.000000
75%,1.254066e+06,2.000000,14.000000,5.000000,1.000000,0.000000,1.000000,0.000000
max,1.426312e+06,6.000000,19.000000,11.000000,6.000000,7.000000,7.000000,1.000000

In [ ]:
deliveries_data.duplicated().sum()

0

In [ ]:
deliveries_data.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [ ]:
columns_to_drop = ['extras_type', 'player_dismissed', 'dismissal_kind', 'fielder']
deliveries_data = deliveries_data.drop(columns=columns_to_drop, axis=1)

In [ ]:
deliveries_data.isnull().sum()

match_id        0
inning          0
batting_team    0
bowling_team    0
over            0
ball            0
batter          0
bowler          0
non_striker     0
batsman_runs    0
extra_runs      0
total_runs      0
is_wicket       0
dtype: int64

In [ ]:
# Runs by players
player_match_stats = df.groupby(['batter', 'match_id'])['batsman_runs'].sum().reset_index()

player_stats = player_match_stats.groupby('batter').agg(
    mean_runs=('batsman_runs', 'mean'),
    median_runs=('batsman_runs', 'median'),
    mode_runs=('batsman_runs', lambda x: x.mode()[0] if not x.mode().empty else None),
    total_runs=('batsman_runs', 'sum')
)
player_stats = player_stats.sort_values(by='total_runs', ascending=False)
player_stats.head(20)

                mean_runs  median_runs  mode_runs  total_runs
batter
V Kohli         32.844262         25.0          0        8014
S Dhawan        30.628959         25.0          0        6769
RG Sharma       26.414343         19.0          0        6630
DA Warner       35.690217         33.0          0        6567
SK Raina        27.680000         23.0          2        5536
MS Dhoni        22.995614         21.0          5        5243
AB de Villiers  30.476471         21.5          0        5181
CH Gayle        35.439716         23.0          0        4997
RV Uthappa      25.147208         22.0          1        4954
KD Karthik      20.785408         17.0          0        4843
KL Rahul        38.434426         29.0          0        4689
AM Rahane       27.146199         19.0          0        4642
F du Plessis    33.123188         29.0          0        4571
SV Samson       27.277778         20.0          0        4419
AT Rayudu       23.502703         19.0          0        4348
G Gambhir       27.927152         19.0          0        4217
SR Watson       27.517730         19.0          1        3880
MK Pandey       24.424051         18.5          0        3859
SA Yadav        26.622222         21.0          0        3594
JC Buttler      33.801887         23.5          0        3583

In [ ]:
# Averages of  batting players

total_runs = deliveries_data.groupby('batter')['batsman_runs'].sum()
times_out = deliveries_data[deliveries_data['is_wicket'] == 1].groupby('batter')['is_wicket'].count()

batsman_stats = pd.DataFrame({'total_runs': total_runs, 'times_out': times_out})

# Calculating the batting average
batsman_stats['batting_average'] = batsman_stats['total_runs'] / batsman_stats['times_out']

batsman_stats = batsman_stats.sort_values(by='total_runs', ascending=False)
batsman_stats.head(20)

                total_runs  times_out  batting_average
batter
V Kohli               8014      218.0        36.761468
S Dhawan              6769      194.0        34.891753
RG Sharma             6630      232.0        28.577586
DA Warner             6567      164.0        40.042683
SK Raina              5536      168.0        32.952381
MS Dhoni              5243      149.0        35.187919
AB de Villiers        5181      125.0        41.448000
CH Gayle              4997      128.0        39.039062
RV Uthappa            4954      184.0        26.923913
KD Karthik            4843      189.0        25.624339
KL Rahul              4689      106.0        44.235849
AM Rahane             4642      156.0        29.756410
F du Plessis          4571      125.0        36.568000
SV Samson             4419      142.0        31.119718
AT Rayudu             4348      152.0        28.605263
G Gambhir             4217      135.0        31.237037
SR Watson             3880      126.0        30.793651
MK Pandey             3859      133.0        29.015038
SA Yadav              3594      112.0        32.089286
JC Buttler            3583       96.0        37.322917

In [ ]:
# Calculating total balls faced by each batter
balls_faced = deliveries_data.groupby('batter').size()

In [ ]:
# Calculating total runs, times out, and balls faced
total_runs = df.groupby('batter')['batsman_runs'].sum()
times_out = df[df['is_wicket'] == 1].groupby('batter')['is_wicket'].count()

batsman_stats = pd.DataFrame({
    'total_runs': total_runs,
    'times_out': times_out,
    'balls_faced': balls_faced
})

In [ ]:
# Calculating batting average
batsman_stats['batting_average'] = batsman_stats['total_runs'] / batsman_stats['times_out']

# Calculating strike rate
batsman_stats['strike_rate'] = (batsman_stats['total_runs'] / batsman_stats['balls_faced']) * 100

In [ ]:
# Calculating total 100s and 50s
player_match_stats = df.groupby(['batter', 'match_id'])['batsman_runs'].sum().reset_index()
player_match_stats['hundreds'] = player_match_stats['batsman_runs'].apply(lambda x: 1 if x >= 100 else 0)
player_match_stats['fifties'] = player_match_stats['batsman_runs'].apply(lambda x: 1 if 50 <= x < 100 else 0)

hundreds = player_match_stats.groupby('batter')['hundreds'].sum()
fifties = player_match_stats.groupby('batter')['fifties'].sum()


batsman_stats['total_hundreds'] = hundreds
batsman_stats['total_fifties'] = fifties
batsman_stats.fillna({'total_hundreds': 0, 'total_fifties': 0}, inplace=True)

batsman_stats = batsman_stats.sort_values(by='total_runs', ascending=False)
batsman_stats.head(20)

,total_runs,times_out,balls_faced,batting_average,strike_rate,total_hundreds,total_fifties
batter,,,,,,,
V Kohli,8014,218.0,6236,36.761468,128.511867,8,56
S Dhawan,6769,194.0,5483,34.891753,123.454313,2,51
RG Sharma,6630,232.0,5183,28.577586,127.918194,2,43
DA Warner,6567,164.0,4849,40.042683,135.429986,4,62
SK Raina,5536,168.0,4177,32.952381,132.535312,1,39
MS Dhoni,5243,149.0,3947,35.187919,132.835065,0,24
AB de Villiers,5181,125.0,3487,41.448000,148.580442,3,41
CH Gayle,4997,128.0,3516,39.039062,142.121729,6,32
RV Uthappa,4954,184.0,3927,26.923913,126.152279,0,27
KD Karthik,4843,189.0,3687,25.624339,131.353404,0,22
KL Rahul,4689,106.0,3578,44.235849,131.050866,4,37
AM Rahane,4642,156.0,3858,29.756410,120.321410,2,30
F du Plessis,4571,125.0,3435,36.568000,133.071325,0,37
SV Samson,4419,142.0,3270,31.119718,135.137615,3,25
AT Rayudu,4348,152.0,3490,28.605263,124.584527,1,22
G Gambhir,4217,135.0,3524,31.237037,119.665153,0,36
SR Watson,3880,126.0,2892,30.793651,134.163209,4,21
MK Pandey,3859,133.0,3288,29.015038,117.366180,1,22
SA Yadav,3594,112.0,2522,32.089286,142.505948,2,24
JC Buttler,3583,96.0,2519,37.322917,142.238984,7,19

# **TOP 10 BATSMAN**

In [ ]:
# finding the best batsman
batsman_stats['composite_score'] = (
    (batsman_stats['total_runs'] / batsman_stats['total_runs'].max()) * 0.25 +
    (batsman_stats['batting_average'] / batsman_stats['batting_average'].max()) * 0.20 +
    (batsman_stats['strike_rate'] / batsman_stats['strike_rate'].max()) * 0.20 +
    (batsman_stats['total_hundreds'] / batsman_stats['total_hundreds'].max()) * 0.15 +
    (batsman_stats['total_fifties'] / batsman_stats['total_fifties'].max()) * 0.10 +
    ((1 / batsman_stats['times_out']) / (1 / batsman_stats['times_out']).max()) * 0.10
)

# Sorting players by composite score
top_10_players = batsman_stats.sort_values(by='composite_score', ascending=False).head(10)

# Displaying the top 10 players as a table
top_10_players[['total_runs', 'batting_average', 'strike_rate', 'total_hundreds', 'total_fifties', 'balls_faced', 'composite_score']]

,total_runs,batting_average,strike_rate,total_hundreds,total_fifties,balls_faced,composite_score
batter,,,,,,,
V Kohli,8014,36.761468,128.511867,8,56,6236,0.660005
DA Warner,6567,40.042683,135.429986,4,62,4849,0.561763
CH Gayle,4997,39.039062,142.121729,6,32,3516,0.504251
S Dhawan,6769,34.891753,123.454313,2,51,5483,0.493038
AB de Villiers,5181,41.448000,148.580442,3,41,3487,0.478056
KL Rahul,4689,44.235849,131.050866,4,37,3578,0.469799
RG Sharma,6630,28.577586,127.918194,2,43,5183,0.464339
JC Buttler,3583,37.322917,142.238984,7,19,2519,0.454361
SK Raina,5536,32.952381,132.535312,1,39,4177,0.418195
SV Samson,4419,31.119718,135.137615,3,25,3270,0.395948

# **TOP 10 BLOWERS**

In [ ]:
# Wickets by players
wickets_data = df[df['is_wicket'] == 1]

bowler_match_wickets = wickets_data.groupby(['bowler', 'match_id'])['is_wicket'].sum().reset_index()

bowler_stats = bowler_match_wickets.groupby('bowler').agg(
    mean_wickets=('is_wicket', 'mean'),
    median_wickets=('is_wicket', 'median'),
    mode_wickets=('is_wicket', lambda x: x.mode()[0] if not x.mode().empty else None),
    total_wickets=('is_wicket', 'sum')
)
bowler_stats = bowler_stats.sort_values(by='total_wickets', ascending=False)

bowler_stats.head(20)

                 mean_wickets  median_wickets  mode_wickets  total_wickets
bowler
YS Chahal            1.745902             1.5             1            213
DJ Bravo             1.754237             2.0             1            207
PP Chawla            1.570312             1.0             1            201
SP Narine            1.680672             1.0             1            200
R Ashwin             1.500000             1.0             1            198
B Kumar              1.695652             1.0             1            195
SL Malinga           2.000000             2.0             1            188
A Mishra             1.710280             1.0             1            183
JJ Bumrah            2.022222             2.0             1            182
RA Jadeja            1.673267             1.0             1            169
UT Yadav             1.811111             2.0             1            163
Harbhajan Singh      1.694737             1.0             1            161
Rashid Khan          1.635417             1.0             1            157
Sandeep Sharma       1.700000             1.0             1            153
HV Patel             1.841463             2.0             1            151
MM Sharma            1.934211             2.0             1            147
Mohammed Shami       1.734940             2.0             1            144
AR Patel             1.439560             1.0             1            131
TA Boult             1.580247             1.0             1            128
R Vinay Kumar        1.867647             2.0             1            127

In [ ]:
# Calculating total wickets taken by each bowler
total_wickets = df[df['is_wicket'] == 1].groupby('bowler')['is_wicket'].count()

# Calculating total runs conceded by each bowler
runs_conceded = df.groupby('bowler')['total_runs'].sum()

# Calculating total balls bowled by each bowler
balls_bowled = df[df['extra_runs'] == 0].groupby('bowler').size()

# Calculating economy rate
economy_rate = runs_conceded / (balls_bowled / 6)

# Calculating bowling average
bowling_average = runs_conceded / total_wickets

# Calculating strike rate
bowling_strike_rate = balls_bowled / total_wickets


bowler_stats = pd.DataFrame({
    'total_wickets': total_wickets,
    'runs_conceded': runs_conceded,
    'balls_bowled': balls_bowled,
    'economy_rate': economy_rate,
    'bowling_average': bowling_average,
    'bowling_strike_rate': bowling_strike_rate
})
bowler_stats = bowler_stats.sort_values(by='total_wickets', ascending=False)
bowler_stats.head(20)

,total_wickets,runs_conceded,balls_bowled,economy_rate,bowling_average,bowling_strike_rate
bowler,,,,,,
YS Chahal,213.0,4681,3469,8.096281,21.976526,16.286385
DJ Bravo,207.0,4436,3064,8.686684,21.429952,14.801932
PP Chawla,201.0,5179,3817,8.140948,25.766169,18.990050
SP Narine,200.0,4672,4019,6.974869,23.360000,20.095000
R Ashwin,198.0,5435,4470,7.295302,27.449495,22.575758
B Kumar,195.0,5051,3813,7.948072,25.902564,19.553846
SL Malinga,188.0,3486,2754,7.594771,18.542553,14.648936
A Mishra,183.0,4193,3336,7.541367,22.912568,18.229508
JJ Bumrah,182.0,3840,3003,7.672328,21.098901,16.500000
RA Jadeja,169.0,4917,3784,7.796512,29.094675,22.390533
UT Yadav,163.0,4442,2981,8.940624,27.251534,18.288344
Harbhajan Singh,161.0,4101,3367,7.307989,25.472050,20.913043
Rashid Khan,157.0,3340,2820,7.106383,21.273885,17.961783
Sandeep Sharma,153.0,3758,2787,8.090420,24.562092,18.215686
HV Patel,151.0,3215,2115,9.120567,21.291391,14.006623
MM Sharma,147.0,3278,2232,8.811828,22.299320,15.183673
Mohammed Shami,144.0,3486,2382,8.780856,24.208333,16.541667
AR Patel,131.0,3824,3059,7.500490,29.190840,23.351145
TA Boult,128.0,3286,2307,8.546164,25.671875,18.023438
R Vinay Kumar,127.0,3041,2089,8.734323,23.944882,16.448819

In [ ]:
# Finding the best bowlers
bowler_stats['composite_score'] = (
    (bowler_stats['total_wickets'] / bowler_stats['total_wickets'].max()) * 0.30 +
    ((1 / bowler_stats['economy_rate']) / (1 / bowler_stats['economy_rate']).max()) * 0.25 +
    ((1 / bowler_stats['bowling_average']) / (1 / bowler_stats['bowling_average']).max()) * 0.20 +
    ((1 / bowler_stats['bowling_strike_rate']) / (1 / bowler_stats['bowling_strike_rate']).max()) * 0.25
)

top_10_bowlers = bowler_stats.sort_values(by='composite_score', ascending=False).head(10)
top_10_bowlers[['total_wickets', 'economy_rate', 'bowling_average', 'bowling_strike_rate', 'composite_score']]

,total_wickets,economy_rate,bowling_average,bowling_strike_rate,composite_score
bowler,,,,,
YS Chahal,213.0,8.096281,21.976526,16.286385,0.315350
DJ Bravo,207.0,8.686684,21.429952,14.801932,0.308439
PP Chawla,201.0,8.140948,25.766169,18.990050,0.296263
SP Narine,200.0,6.974869,23.360000,20.095000,0.294131
R Ashwin,198.0,7.295302,27.449495,22.575758,0.289947
B Kumar,195.0,7.948072,25.902564,19.553846,0.287433
SL Malinga,188.0,7.594771,18.542553,14.648936,0.281855
JJ Bumrah,182.0,7.672328,21.098901,16.500000,0.271490
A Mishra,183.0,7.541367,22.912568,18.229508,0.271461
RA Jadeja,169.0,7.796512,29.094675,22.390533,0.249194