In [ ]:
import pandas as pd
import numpy as np

In [ ]:
deliveries=pd.read_csv("/content/drive/MyDrive/Copy of deliveries.csv")

In [ ]:
deliveries.head(10)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
5,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
6,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,7,BB McCullum,P Kumar,SC Ganguly,0,1,1,legbyes,0,NaN,NaN,NaN
7,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,BB McCullum,Z Khan,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
8,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN
9,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN

In [ ]:
deliveries.sample(10)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
33770,419133,1,Royal Challengers Bangalore,Chennai Super Kings,16,2,CL White,M Muralitharan,KP Pietersen,0,0,0,NaN,0,NaN,NaN,NaN
102902,734001,1,Sunrisers Hyderabad,Mumbai Indians,8,6,KL Rahul,JJ Bumrah,AJ Finch,1,0,1,NaN,0,NaN,NaN,NaN
164108,1136618,1,Kolkata Knight Riders,Rajasthan Royals,15,2,AD Russell,IS Sodhi,KD Karthik,1,0,1,NaN,0,NaN,NaN,NaN
217893,1304087,2,Delhi Capitals,Kolkata Knight Riders,6,3,DA Warner,SP Narine,Lalit Yadav,4,0,4,NaN,0,NaN,NaN,NaN
158526,1136595,1,Royal Challengers Bangalore,Chennai Super Kings,1,5,PA Patel,L Ngidi,V Kohli,4,0,4,NaN,0,NaN,NaN,NaN
64897,548332,2,Chennai Super Kings,Rajasthan Royals,7,1,S Badrinath,GB Hogg,F du Plessis,1,0,1,NaN,0,NaN,NaN,NaN
81337,598018,1,Sunrisers Hyderabad,Pune Warriors,18,3,A Mishra,AD Mathews,A Ashish Reddy,1,0,1,NaN,0,NaN,NaN,NaN
233505,1359505,2,Mumbai Indians,Punjab Kings,17,3,TH David,Arshdeep Singh,SA Yadav,1,0,1,NaN,0,NaN,NaN,NaN
125397,980925,1,Kings XI Punjab,Kolkata Knight Riders,16,3,AR Patel,UT Yadav,SE Marsh,2,0,2,NaN,0,NaN,NaN,NaN
21519,392217,1,Rajasthan Royals,Chennai Super Kings,6,5,GC Smith,M Muralitharan,SA Asnodkar,0,1,1,legbyes,0,NaN,NaN,NaN

In [ ]:
deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

In [ ]:
team_dup={"Delhi Daredevils":"Delhi Capitals",
                  "Rising Pune Supergiants":"Rising Pune Supergiant",
                  "Royal Challengers Bengaluru":"Royal Challengers Bangalore",
                  "Gujarat Lions":"Gujarat Titans"}

In [ ]:
deliveries.replace(to_replace=team_dup,inplace=True)
deliveries['bowling_team'].sample(20)

235536                 Delhi Capitals
94558                  Mumbai Indians
19381     Royal Challengers Bangalore
84738             Sunrisers Hyderabad
72855                  Mumbai Indians
187956            Chennai Super Kings
218506                 Mumbai Indians
86504                  Mumbai Indians
153098            Chennai Super Kings
143404          Kolkata Knight Riders
29262                  Mumbai Indians
4648              Chennai Super Kings
132235    Royal Challengers Bangalore
176685            Sunrisers Hyderabad
81598                Rajasthan Royals
23146                  Delhi Capitals
67339           Kolkata Knight Riders
172545            Sunrisers Hyderabad
4634                   Delhi Capitals
42930           Kolkata Knight Riders
Name: bowling_team, dtype: object

In [ ]:
deliveries.describe()

,match_id,inning,over,ball,batsman_runs,extra_runs,total_runs,is_wicket
count,2.609200e+05,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000
mean,9.070665e+05,1.483531,9.197677,3.624486,1.265001,0.067806,1.332807,0.049632
std,3.679913e+05,0.502643,5.683484,1.814920,1.639298,0.343265,1.626416,0.217184
min,3.359820e+05,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,5.483340e+05,1.000000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000
50%,9.809670e+05,1.000000,9.000000,4.000000,1.000000,0.000000,1.000000,0.000000
75%,1.254066e+06,2.000000,14.000000,5.000000,1.000000,0.000000,1.000000,0.000000
max,1.426312e+06,6.000000,19.000000,11.000000,6.000000,7.000000,7.000000,1.000000

statistics for runs

In [ ]:
player_runs = deliveries.groupby(['match_id','batter'])['batsman_runs'].sum().reset_index()
player_runs= deliveries.groupby('batter')['batsman_runs'].sum().reset_index()
player_runs.columns=["batter","total_runs"]
player_runs

             batter  total_runs
0    A Ashish Reddy         280
1          A Badoni         634
2        A Chandila           4
3          A Chopra          53
4       A Choudhary          25
..              ...         ...
668   Yashpal Singh          47
669     Younis Khan           3
670   Yudhvir Singh          22
671    Yuvraj Singh        2754
672          Z Khan         117

[673 rows x 2 columns]

In [ ]:
batter_knockout=deliveries.groupby("batter")["is_wicket"].sum()
batter_info=pd.merge(player_runs,batter_knockout,on="batter",how="left")
batter_info.columns=["batter","total_runs","total_times_out"]
batter_knockout.head(5)

batter
A Ashish Reddy    15
A Badoni          26
A Chandila         1
A Chopra           5
A Choudhary        2
Name: is_wicket, dtype: int64

In [ ]:
total_matches=deliveries.groupby("batter")["match_id"].nunique().reset_index()
total_matches.columns=["batter","total_matches_played"]
batter_stats=pd.merge(batter_info,total_matches,on="batter",how="left")

In [ ]:
batter_stats

             batter  total_runs  total_times_out  total_matches_played
0    A Ashish Reddy         280               15                    23
1          A Badoni         634               26                    35
2        A Chandila           4                1                     2
3          A Chopra          53                5                     6
4       A Choudhary          25                2                     3
..              ...         ...              ...                   ...
668   Yashpal Singh          47                4                     4
669     Younis Khan           3                1                     1
670   Yudhvir Singh          22                4                     4
671    Yuvraj Singh        2754              109                   126
672          Z Khan         117               15                    27

[673 rows x 4 columns]

In [ ]:
batter_stats["batting_average"]=batter_stats["total_runs"]/batter_stats["total_times_out"]

In [ ]:
batter_stats["batting_average"].replace(np.inf,np.nan,inplace=True)
batter_stats.loc[batter_stats["total_times_out"]==0,"batting_average"]=np.nan
top_5_batter_average=batter_stats.sort_values(by="batting_average",ascending=False)
top_5_batter_average.head(5)

<ipython-input-30-c8827ec23f65>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  batter_stats["batting_average"].replace(np.inf,np.nan,inplace=True)

,batter,total_runs,total_times_out,total_matches_played,batting_average
230,Iqbal Abdulla,88,1,13,88.000000
648,Vivrant Sharma,69,1,1,69.000000
370,MN van Wyk,167,3,5,55.666667
432,PD Collingwood,203,4,7,50.750000
96,B Sai Sudharsan,1034,21,25,49.238095

In [ ]:
batter_stats["player_score"]=(batter_stats["batting_average"]+(batter_stats["total_runs"]/1000)+(batter_stats["total_matches_played"]/10))
best_player=batter_stats.sort_values(by="player_score",ascending=False)
best_player.head(5)

,batter,total_runs,total_times_out,total_matches_played,batting_average,player_score
230,Iqbal Abdulla,88,1,13,88.000000,89.388000
631,V Kohli,8014,218,244,36.761468,69.175468
648,Vivrant Sharma,69,1,1,69.000000,69.169000
147,DA Warner,6567,164,184,40.042683,65.009683
512,S Dhawan,6769,194,221,34.891753,63.760753

In [ ]:
batter_stats = deliveries.groupby('batter').agg(
    total_runs=('batsman_runs', 'sum'),
    balls_faced=('ball', 'count'),
    dismissals=('is_wicket', 'sum'),
    centuries=('batsman_runs', lambda x: (x >= 100).sum()),
    fifties=('batsman_runs', lambda x: ((x >= 50) & (x < 100)).sum())
).reset_index()

# Calculating batting average and strike rate
batter_stats['batting_average'] = batter_stats['total_runs'] / batter_stats['dismissals']
batter_stats['strike_rate'] = (batter_stats['total_runs'] / batter_stats['balls_faced']) * 100

# Replacing  NaN averages for not-out players with their total runs
batter_stats['batting_average'].fillna(batter_stats['total_runs'], inplace=True)

# :Normalize metrics
batter_stats['normalized_average'] = (batter_stats['batting_average'] / batter_stats['batting_average'].max()) * 100
batter_stats['normalized_strike_rate'] = (batter_stats['strike_rate'] / batter_stats['strike_rate'].max()) * 100
batter_stats['normalized_centuries'] = (batter_stats['centuries'] / batter_stats['centuries'].max()) * 100
batter_stats['normalized_fifties'] = (batter_stats['fifties'] / batter_stats['fifties'].max()) * 100

# Handle cases with no centuries or fifties (avoid NaN in normalization)
batter_stats['normalized_centuries'].fillna(0, inplace=True)
batter_stats['normalized_fifties'].fillna(0, inplace=True)

#Compute overall score
w1, w2, w3, w4 = 0.3, 0.4, 0.15, 0.05
batter_stats['overall_score'] = (
    batter_stats['normalized_average'] * w1 +
    batter_stats['normalized_strike_rate'] * w2 +
    batter_stats['normalized_centuries'] * w3 +
    batter_stats['normalized_fifties'] * w4
)

# Find the best batter
best_batter = batter_stats.sort_values(by='overall_score', ascending=False).head(5)

# Display results
print("Best Batter Based on Criteria:")
print(best_batter)

Best Batter Based on Criteria:
              batter  total_runs  balls_faced  dismissals  centuries  fifties  \
234  J Fraser-McGurk         330          150           8          0        0
461    R Sai Kishore          13            6           1          0        0
629         Umar Gul          39           19           3          0        0
583    Shahid Afridi          81           46           8          0        0
652         WG Jacks         230          133           6          0        0

     batting_average  strike_rate  normalized_average  normalized_strike_rate  \
234        41.250000   220.000000                 0.0               73.333333
461        13.000000   216.666667                 0.0               72.222222
629        13.000000   205.263158                 0.0               68.421053
583        10.125000   176.086957                 0.0               58.695652
652        38.333333   172.932331                 0.0               57.644110

     normalized_centuries  normalized_fifties  overall_score
234                   0.0                 0.0      29.333333
461                   0.0                 0.0      28.888889
629                   0.0                 0.0      27.368421
583                   0.0                 0.0      23.478261
652                   0.0                 0.0      23.057644

<ipython-input-40-388ecabae72a>:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  batter_stats['batting_average'].fillna(batter_stats['total_runs'], inplace=True)
<ipython-input-40-388ecabae72a>:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  batter_stats['normalized_centuries'].fillna(0, inplace=True)
<ipython-input-40-388ecabae72a>:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  batter_stats['normalized_fifties'].fillna(0, inplace=True)

statistics for wickets

In [ ]:
team_runs_stats=deliveries.groupby('batting_team')['batsman_runs'].agg(['mean','median'])
team_runs_stats['mode'] = deliveries.groupby('batting_team')['batsman_runs'].apply(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
team_runs_stats

                                 mean  median  mode
batting_team
Chennai Super Kings          1.282294     1.0     0
Deccan Chargers              1.204893     1.0     0
Delhi Capitals               1.252893     1.0     0
Gujarat Lions                1.298093     1.0     1
Gujarat Titans               1.339097     1.0     1
Kings XI Punjab              1.260311     1.0     0
Kochi Tuskers Kerala         1.111252     1.0     0
Kolkata Knight Riders        1.258691     1.0     0
Lucknow Super Giants         1.311296     1.0     0
Mumbai Indians               1.270668     1.0     0
Pune Warriors                1.109682     1.0     0
Punjab Kings                 1.323284     1.0     0
Rajasthan Royals             1.260346     1.0     0
Rising Pune Supergiant       1.244828     1.0     1
Royal Challengers Bangalore  1.285648     1.0     0
Sunrisers Hyderabad          1.265440     1.0     1

In [ ]:
wickets = deliveries[deliveries['is_wicket'] == 1]

In [ ]:
wickets.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12950 entries, 33 to 260909
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   match_id          12950 non-null  int64
 1   inning            12950 non-null  int64
 2   batting_team      12950 non-null  object
 3   bowling_team      12950 non-null  object
 4   over              12950 non-null  int64
 5   ball              12950 non-null  int64
 6   batter            12950 non-null  object
 7   bowler            12950 non-null  object
 8   non_striker       12950 non-null  object
 9   batsman_runs      12950 non-null  int64
 10  extra_runs        12950 non-null  int64
 11  total_runs        12950 non-null  int64
 12  extras_type       63 non-null     object
 13  is_wicket         12950 non-null  int64
 14  player_dismissed  12950 non-null  object
 15  dismissal_kind    12950 non-null  object
 16  fielder           9354 non-null   object
dtypes: int64(8), object(9)
memory usage: 1.8+ MB

In [ ]:
wicket_stats=wickets['bowler'].value_counts()
wicket_stats

bowler
YS Chahal          213
DJ Bravo           207
PP Chawla          201
SP Narine          200
R Ashwin           198
                  ...
CJ McKay             1
GR Napier            1
AA Jhunjhunwala      1
GH Vihari            1
Shashank Singh       1
Name: count, Length: 455, dtype: int64