In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('deliveries dataset if.csv')

In [5]:
df1 = pd.read_csv('matches data set if.csv')

In [7]:
# Checking for missing values
print(df.isnull().sum())
# Print the cleaned dataframe info
print(df.info())

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB
None

In [9]:
# Check for missing values
print(df1.isnull().sum())
# Print the cleaned dataframe info
print(df1.info())

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB
None

In [11]:
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [13]:
df1.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [15]:
df.iloc[0]

match_id                                 335982
inning                                        1
batting_team              Kolkata Knight Riders
bowling_team        Royal Challengers Bangalore
over                                          0
ball                                          1
batter                               SC Ganguly
bowler                                  P Kumar
non_striker                         BB McCullum
batsman_runs                                  0
extra_runs                                    1
total_runs                                    1
extras_type                             legbyes
is_wicket                                     0
player_dismissed                            NaN
dismissal_kind                              NaN
fielder                                     NaN
Name: 0, dtype: object

In [17]:
df1.iloc[0]

id                                      335982
season                                 2007/08
city                                 Bangalore
date                                2008-04-18
match_type                              League
player_of_match                    BB McCullum
venue                    M Chinnaswamy Stadium
team1              Royal Challengers Bangalore
team2                    Kolkata Knight Riders
toss_winner        Royal Challengers Bangalore
toss_decision                            field
winner                   Kolkata Knight Riders
result                                    runs
result_margin                            140.0
target_runs                              223.0
target_overs                              20.0
super_over                                   N
method                                     NaN
umpire1                              Asad Rauf
umpire2                            RE Koertzen
Name: 0, dtype: object

In [19]:
df.iloc[:,0]

0          335982
1          335982
2          335982
3          335982
4          335982
           ...
260915    1426312
260916    1426312
260917    1426312
260918    1426312
260919    1426312
Name: match_id, Length: 260920, dtype: int64

In [21]:
df1.iloc[:,0]

0        335982
1        335983
2        335984
3        335985
4        335986
         ...
1090    1426307
1091    1426309
1092    1426310
1093    1426311
1094    1426312
Name: id, Length: 1095, dtype: int64

In [23]:
df.batter.describe()

count      260920
unique        673
top       V Kohli
freq         6236
Name: batter, dtype: object

In [25]:
df1.city.describe()

count       1044
unique        36
top       Mumbai
freq         173
Name: city, dtype: object

In [29]:
df.total_runs.mean()

1.3328069906484745

In [31]:
df1.target_runs.mean()

165.68406593406593

In [33]:
df.batter.unique()

array(['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey',
       'Mohammad Hafeez', 'R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis',
       'CL White', 'MV Boucher', 'B Akhil', 'AA Noffke', 'P Kumar',
       'Z Khan', 'SB Joshi', 'PA Patel', 'ML Hayden', 'MEK Hussey',
       'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'K Goel',
       'JR Hopes', 'KC Sangakkara', 'Yuvraj Singh', 'SM Katich',
       'IK Pathan', 'T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif',
       'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne',
       'SK Trivedi', 'G Gambhir', 'V Sehwag', 'S Dhawan', 'L Ronchi',
       'ST Jayasuriya', 'DJ Thornely', 'RV Uthappa', 'PR Shah',
       'AM Nayar', 'SM Pollock', 'Harbhajan Singh', 'S Chanderpaul',
       'LRPL Taylor', 'AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxman',
       'A Symonds', 'RG Sharma', 'SB Styris', 'AS Yadav', 'SB Bangar',
       'WPUJC Vaas', 'RP Singh', 'WP Saha', 'LR Shukla',
       'DPMD Jayawardene', 'S Sohal', 'B Lee', 'PP Chawla', 'WA Mota',
       'Kamran Akmal', 'Shahid Afridi', 'DJ Bravo', 'MA Khote', 'A Nehra',
       'GC Smith', 'Pankaj Singh', 'RR Sarwan', 'S Sreesanth',
       'VRV Singh', 'SS Tiwary', 'DS Kulkarni', 'R Vinay Kumar',
       'AB Agarkar', 'M Kartik', 'I Sharma', 'AM Rahane', 'Shoaib Malik',
       'MK Tiwary', 'KD Karthik', 'R Bhatia', 'MF Maharoof', 'VY Mahesh',
       'TM Srivastava', 'B Chipli', 'DW Steyn', 'DB Das', 'MK Pandey',
       'HH Gibbs', 'DNT Zoysa', 'D Kalyankrishna', 'SE Marsh',
       'SA Asnodkar', 'Sohail Tanvir', 'Salman Butt', 'BJ Hodge',
       'Umar Gul', 'AB Dinda', 'SP Fleming', 'S Vidyut', 'JA Morkel',
       'AB de Villiers', 'LPC Silva', 'DB Ravi Teja', 'Misbah-ul-Haq',
       'YV Takawale', 'RR Raje', 'PJ Sangwan', 'Mohammad Asif',
       'GD McGrath', 'Joginder Sharma', 'MS Gony', 'M Muralitharan',
       'M Ntini', 'DT Patil', 'A Kumble', 'S Anirudha', 'MM Patel',
       'CK Kapugedera', 'A Chopra', 'T Taibu', 'J Arunkumar', 'PP Ojha',
       'SP Goswami', 'SR Tendulkar', 'U Kaul', 'TM Dilshan', 'A Mishra',
       'AD Mascarenhas', 'NK Patel', 'LA Pomersbach', 'Iqbal Abdulla',
       'Younis Khan', 'PM Sarvesh Kumar', 'DP Vijaykumar',
       'Shoaib Akhtar', 'Abdur Razzak', 'H Das', 'DR Smith', 'SD Chitnis',
       'CRD Fernando', 'VS Yeligati', 'L Balaji', 'A Mukund', 'RR Powar',
       'JP Duminy', 'A Flintoff', 'T Thushara', 'JD Ryder',
       'KP Pietersen', 'T Henderson', 'Kamran Khan', 'RS Bopara',
       'CH Gayle', 'MC Henriques', 'R Bishnoi', 'FH Edwards', 'KV Sharma',
       'PC Valthaty', 'RJ Quiney', 'AS Raut', 'Yashpal Singh', 'M Manhas',
       'AA Bilakhia', 'AN Ghosh', 'BAW Mendis', 'DL Vettori',
       'MN van Wyk', 'RE van der Merwe', 'TL Suman', 'Shoaib Ahmed',
       'GR Napier', 'KP Appanna', 'LA Carseldine', 'NV Ojha',
       'SM Harwood', 'M Vijay', 'SB Jakati', 'DA Warner', 'RJ Harris',
       'D du Preez', 'M Morkel', 'AD Mathews', 'J Botha', 'C Nanda',
       'SL Malinga', 'Mashrafe Mortaza', 'A Singh', 'GJ Bailey',
       'AB McDonald', 'Y Nagar', 'SS Shaikh', 'R Ashwin',
       'Mohammad Ashraful', 'CA Pujara', 'OA Shah', 'Anirudh Singh',
       'Jaskaran Singh', 'AP Tare', 'AT Rayudu', 'R Sathish', 'R McLaren',
       'AA Jhunjhunwala', 'P Dogra', 'A Uniyal', 'MS Bisla', 'YA Abdulla',
       'EJG Morgan', 'JM Kemp', 'S Tyagi', 'RS Gavaskar', 'SE Bond',
       'KA Pollard', 'S Ladda', 'DP Nannes', 'MJ Lumb', 'DR Martyn',
       'S Narwal', 'AB Barath', 'Bipul Sharma', 'FY Fazal', 'AC Voges',
       'MD Mishra', 'UT Yadav', 'J Theron', 'SJ Srivastava', 'R Sharma',
       'Mandeep Singh', 'KM Jadhav', 'SW Tait', 'KB Arun Karthik',
       'KAJ Roach', 'PD Collingwood', 'CK Langeveldt', 'VS Malik',
       'A Mithun', 'AP Dole', 'AN Ahmed', 'RS Sodhi', 'DE Bollinger',
       'S Sriram', 'B Sumanth', 'C Madan', 'AG Paunikar', 'MR Marsh',
       'AJ Finch', 'STR Binny', 'Harmeet Singh', 'IR Jaggi',
       'DT Christian', 'RV Gomez', 'MA Agarwal', 'AUK Pathan',
       'UBT Chand', 'DJ Jacobs', 'Sunny Singh', 'NJ Rimmington',
       'AL Menaria', 'WD Parnell', 'JJ van der Wath', 'R Ninan',
       'S Aravind', 'MS Wade', 'TD Paine', 'SB Wagh', 'AC Thomas',
       'JEC Franklin', 'Shakib Al Hasan', 'DH Yagnik', 'S Randiv',
       'BJ Haddin', 'NLTC Perera', 'NL McCullum', 'JE Taylor',
       'J Syed Mohammad', 'RN ten Doeschate', 'TR Birt', 'AG Murtaza',
       'Harpreet Singh', 'M Klinger', 'AC Blizzard', 'I Malhotra',
       'L Ablish', 'CA Ingram', 'S Nadeem', 'P Parameswaran',
       'CJ Ferguson', 'VR Aaron', 'AA Chavan', 'ND Doshi', 'B Kumar',
       'Y Gnaneswara Rao', 'S Rana', 'BA Bhatt', 'F du Plessis',
       'RE Levi', 'GJ Maxwell', 'SPD Smith', 'MN Samuels', 'SA Yadav',
       'KK Cooper', 'JP Faulkner', 'HV Patel', 'DAJ Bracewell',
       'DJ Harris', 'Ankit Sharma', 'SP Narine', 'GB Hogg', 'RR Bhatkal',
       'CJ McKay', 'N Saini', 'DA Miller', 'Azhar Mahmood', 'P Negi',
       'RJ Peterson', 'KMDN Kulasekara', 'A Ashish Reddy',
       'V Pratap Singh', 'BB Samantray', 'MJ Clarke', 'Gurkeerat Singh',
       'AP Majumdar', 'PA Reddy', 'K Upadhyay', 'P Awana', 'AD Russell',
       'A Chandila', 'CA Lynn', 'Sunny Gupta', 'MC Juneja', 'KK Nair',
       'GH Vihari', 'MDKJ Perera', 'R Shukla', 'B Laughlin', 'AS Rajpoot',
       'M Vohra', 'JD Unadkat', 'Mohammed Shami', 'BMAJ Mendis',
       'R Rampaul', 'CH Morris', 'SV Samson', 'SMSM Senanayake',
       'BJ Rohrer', 'KL Rahul', 'Q de Kock', 'R Dhawan', 'MG Johnson',
       'LJ Wright', 'IC Pandey', 'CM Gautam', 'X Thalaivan Sargunam',
       'DJG Sammy', 'KW Richardson', 'MM Sharma', 'UA Birla',
       'Parvez Rasool', 'Sandeep Sharma', 'S Kaul', 'Sachin Baby',
       'PV Tambe', 'NM Coulter-Nile', 'CJ Anderson', 'NJ Maddinson',
       'AR Patel', 'JJ Bumrah', 'JDS Neesham', 'TG Southee', 'MA Starc',
       'BR Dunk', 'RR Rossouw', 'Shivam Sharma', 'YS Chahal',
       'LMP Simmons', 'VH Zol', 'BCJ Cutting', 'Imran Tahir',
       'BE Hendricks', 'S Gopal', 'M de Lange', 'R Tewatia', 'JO Holder',
       'Karanveer Singh', 'SS Iyer', 'DJ Hooda', 'Anureet Singh',
       'KS Williamson', 'SA Abbott', 'J Suchith', 'RG More', 'HH Pandya',
       'D Wiese', 'SN Khan', 'MJ McClenaghan', 'DJ Muthuswami',
       'PJ Cummins', 'SN Thakur', 'JC Buttler', 'CR Brathwaite',
       'MP Stoinis', 'Ishan Kishan', 'C Munro', 'P Sahu', 'KH Pandya',
       'AD Nath', 'MJ Guptill', 'KJ Abbott', 'TM Head', 'M Ashwin',
       'NS Naik', 'RR Pant', 'SW Billings', 'KC Cariappa',
       'PSP Handscomb', 'Swapnil Singh', 'J Yadav', 'UT Khawaja',
       'HM Amla', 'F Behardien', 'BB Sran', 'A Zampa', 'N Rana',
       'S Kaushik', 'ER Dwivedi', 'CJ Jordan', 'TS Mills', 'A Choudhary',
       'BA Stokes', 'JJ Roy', 'Vishnu Vinod', 'Basil Thampi', 'CR Woakes',
       'RA Tripathi', 'DL Chahar', 'V Shankar', 'Rashid Khan',
       'RD Chahar', 'LH Ferguson', 'C de Grandhomme', 'AF Milne',
       'S Badree', 'Mohammad Nabi', 'AJ Tye', 'K Rabada', 'Kuldeep Yadav',
       'Washington Sundar', 'DM Bravo', 'AR Bawne', 'SP Jackson',
       'Ankit Soni', 'TA Boult', 'E Lewis', 'MA Wood', 'RK Singh',
       'DJM Short', 'K Gowtham', 'TK Curran', 'M Markande', 'B Stanlake',
       'Mujeeb Ur Rahman', 'A Dananjaya', 'Shubman Gill', 'Shivam Mavi',
       'Mohammed Siraj', 'H Klaasen', 'RK Bhui', 'JC Archer', 'PP Shaw',
       'LE Plunkett', 'Mustafizur Rahman', 'AD Hales', 'MK Lomror',
       'DR Shorey', 'MM Ali', 'M Prasidh Krishna', 'P Chopra',
       'JPR Scantlebury-Searles', 'Abhishek Sharma', 'IS Sodhi',
       'SO Hetmyer', 'S Dube', 'Navdeep Saini', 'JM Bairstow', 'KMA Paul',
       'Rasikh Salam', 'N Pooran', 'P Ray Barman', 'SM Curran',
       'GC Viljoen', 'Avesh Khan', 'S Lamichhane', 'HF Gurney', 'SD Lad',
       'AS Joseph', 'R Parag', 'MJ Santner', 'JL Denly', 'LS Livingstone',
       'KK Ahmed', 'AJ Turner', 'Harpreet Brar', 'SE Rutherford',
       'Y Prithvi Raj', 'P Simran Singh', 'JL Pattinson', 'A Nortje',
       'T Banton', 'D Padikkal', 'YBK Jaiswal', 'RD Gaikwad',
       'TU Deshpande', 'Abdul Samad', 'PK Garg', 'JR Philippe',
       'Kartik Tyagi', 'KL Nagarkoti', 'CV Varun', 'I Udana',
       'Ravi Bishnoi', 'Shahbaz Ahmed', 'AT Carey', 'N Jagadeesan',
       'T Natarajan', 'P Dubey', 'SS Cottrell', 'Arshdeep Singh',
       'DR Sams', 'M Jansen', 'RM Patidar', 'KA Jamieson',
       'M Shahrukh Khan', 'JA Richardson', 'Lalit Yadav', 'Virat Singh',
       'FA Allen', 'C Sakariya', 'DJ Malan', 'KS Bharat', 'PWH de Silva',
       'VR Iyer', 'GD Phillips', 'GHS Garton', 'AK Markram', 'K Yadav',
       'T Shamsi', 'NT Ellis', 'RV Patel', 'TL Seifert',
       'Anmolpreet Singh', 'Anuj Rawat', 'TH David', 'DP Conway',
       'Tilak Varma', 'R Powell', 'PBB Rajapaksa', 'RA Bawa', 'OF Smith',
       'A Badoni', 'PVD Chameera', 'A Manohar', 'R Shepherd', 'DJ Willey',
       'D Pretorius', 'JM Sharma', 'VG Arora', 'Mukesh Choudhary',
       'Umran Malik', 'D Brevis', 'B Sai Sudharsan', 'Ramandeep Singh',
       'HE van der Dussen', 'SS Prabhudessai', 'Akash Deep',
       'JR Hazlewood', 'KR Sen', 'Aman Hakim Khan', 'HR Shokeen',
       'Yash Dayal', 'DJ Mitchell', 'Shashank Singh', 'B Indrajith',
       'Harshit Rana', 'Mohsin Khan', 'Simarjeet Singh', 'M Theekshana',
       'AS Roy', 'Fazalhaq Farooqi', 'K Kartikeya', 'RP Meredith',
       'KS Sharma', 'T Stubbs', 'R Sanjay Yadav', 'A Tomar', 'PN Mankad',
       'OC McCoy', 'Sikandar Raza', 'Rahmanullah Gurbaz', 'KR Mayers',
       'Mukesh Kumar', 'HC Brook', 'AU Rashid', 'C Green', 'N Wadhera',
       'Arshad Khan', 'Abishek Porel', 'Dhruv Jurel', 'MG Bracewell',
       'MW Short', 'Mohit Rathee', 'YV Dhull', 'Yudhvir Singh',
       'Atharva Taide', 'Liton Das', 'PD Salt', 'Vijaykumar Vyshak',
       'Abdul Basith', 'Arjun Tendulkar', 'JP Behrendorff', 'AJ Hosein',
       'Naveen-ul-Haq', 'Noor Ahmad', 'JE Root', 'KM Asif', 'MD Shanaka',
       'Sanvir Singh', 'Vivrant Sharma', 'DG Nalkande', 'R Ravindra',
       'SD Hope', 'Sumit Kumar', 'Azmatullah Omarzai', 'Naman Dhir',
       'G Coetzee', 'SZ Mulani', 'Sameer Rizvi', 'SH Johnson',
       'Akash Madhwal', 'SB Dubey', 'Mayank Dagar', 'RJW Topley',
       'A Raghuvanshi', 'Ashutosh Sharma', 'Nithish Kumar Reddy',
       'Saurav Chauhan', 'Kumar Kushagra', 'BR Sharath', 'WG Jacks',
       'J Fraser-McGurk', 'Tanush Kotian', 'KA Maharaj',
       'Arshad Khan (2)', 'R Sai Kishore', 'L Wood', 'LB Williams',
       'AA Kulkarni', 'MJ Suthar', 'RJ Gleeson', 'Gulbadin Naib',
       'D Ferreira', 'A Kamboj', 'T Kohler-Cadmore', 'Shivam Singh',
       'V Viyaskanth'], dtype=object)

In [35]:
df1.city.unique()

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', nan, 'Rajkot', 'Kanpur', 'Bengaluru', 'Dubai',
       'Sharjah', 'Navi Mumbai', 'Lucknow', 'Guwahati', 'Mohali'],
      dtype=object)

In [37]:
df.batter.value_counts()

batter
V Kohli           6236
S Dhawan          5483
RG Sharma         5183
DA Warner         4849
SK Raina          4177
                  ...
V Pratap Singh       1
Sunny Gupta          1
YA Abdulla           1
SZ Mulani            1
S Kaushik            1
Name: count, Length: 673, dtype: int64

In [39]:
df1.city.value_counts()

city
Mumbai            173
Kolkata            93
Delhi              90
Chennai            85
Hyderabad          77
Bangalore          65
Chandigarh         61
Jaipur             57
Pune               51
Abu Dhabi          37
Ahmedabad          36
Bengaluru          29
Durban             15
Visakhapatnam      15
Lucknow            14
Dubai              13
Dharamsala         13
Centurion          12
Rajkot             10
Sharjah            10
Indore              9
Navi Mumbai         9
Johannesburg        8
Cuttack             7
Port Elizabeth      7
Ranchi              7
Cape Town           7
Raipur              6
Mohali              5
Kochi               5
Kanpur              4
Kimberley           3
East London         3
Guwahati            3
Nagpur              3
Bloemfontein        2
Name: count, dtype: int64

In [ ]:
df.groupby('batter').batter.count()