In [5]:
import pandas as pd

In [8]:
df = pd.read_csv('deliveries.csv')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

In [17]:
batter_stats = df.groupby('batter').agg(
    total_runs=pd.NamedAgg(column='batsman_runs', aggfunc='sum'),
    total_balls=pd.NamedAgg(column='ball', aggfunc='count'),
    total_fours=pd.NamedAgg(column='batsman_runs', aggfunc=lambda x: (x == 4).sum()),
    total_sixes=pd.NamedAgg(column='batsman_runs', aggfunc=lambda x: (x == 6).sum()),
    total_wickets=pd.NamedAgg(column='is_wicket', aggfunc='sum')
).reset_index()
print(batter_stats)

             batter  total_runs  total_balls  total_fours  total_sixes  \
0    A Ashish Reddy         280          196           16           15
1          A Badoni         634          505           46           24
2        A Chandila           4            7            0            0
3          A Chopra          53           75            7            0
4       A Choudhary          25           20            1            1
..              ...         ...          ...          ...          ...
668   Yashpal Singh          47           67            5            0
669     Younis Khan           3            7            0            0
670   Yudhvir Singh          22           16            1            2
671    Yuvraj Singh        2754         2207          218          149
672          Z Khan         117          141           11            2

     total_wickets
0               15
1               26
2                1
3                5
4                2
..             ...
668              4
669              1
670              4
671            109
672             15

[673 rows x 6 columns]

In [21]:
batter_stats['batting_average'] = batter_stats['total_runs'] / batter_stats['total_wickets'].replace(0, 1)  # Avoid division by zero
batter_stats['strike_rate'] = (batter_stats['total_runs'] / batter_stats['total_balls']) * 100

In [22]:
# Sort players by total runs scored
batter_stats.sort_values(by='total_runs', ascending=False, inplace=True)

In [23]:
#Display the top players
print(batter_stats[['batter', 'total_runs', 'batting_average', 'strike_rate', 'total_fours', 'total_sixes']])

           batter  total_runs  batting_average  strike_rate  total_fours  \
631       V Kohli        8014        36.761468   128.511867          708
512      S Dhawan        6769        34.891753   123.454313          768
477     RG Sharma        6630        28.577586   127.918194          599
147     DA Warner        6567        40.042683   135.429986          663
546      SK Raina        5536        32.952381   132.535312          506
..            ...         ...              ...          ...          ...
517       S Ladda           0         0.000000     0.000000            0
518  S Lamichhane           0         0.000000     0.000000            0
69   Abdur Razzak           0         0.000000     0.000000            0
565   SS Cottrell           0         0.000000     0.000000            0
290       KM Asif           0         0.000000     0.000000            0

     total_sixes
631          273
512          153
477          281
147          236
546          204
..           ...
517            0
518            0
69             0
565            0
290            0

[673 rows x 6 columns]

In [10]:
#task 1:calculate stats fpr runs scored by team and players
#runs by players
players_runs_stats={
    "Mean":df["batsman_runs"].mean(),
    "Median":df["batsman_runs"].median(),
    "Mode":df["batsman_runs"].mode()[0],
    "Standard Deviation":df["batsman_runs"].std(),
}
print("Player run stastatstics:")
print(players_runs_stats)

Player run stastatstics:
{'Mean': 1.265000766518473, 'Median': 1.0, 'Mode': 0, 'Standard Deviation': 1.6392976465835523}

In [12]:
import pandas as pd

team_runs_stats = df.groupby("batting_team")["total_runs"].agg(["mean", "median", lambda x: x.mode()[0], "std"])
# Using a lambda function to get the first mode value
print("Team run statistics:")
print(team_runs_stats)

Team run statistics:
                                 mean  median  <lambda_0>       std
batting_team
Chennai Super Kings          1.348260     1.0           1  1.633026
Deccan Chargers              1.268873     1.0           1  1.574241
Delhi Capitals               1.361228     1.0           1  1.640279
Delhi Daredevils             1.293304     1.0           1  1.579882
Gujarat Lions                1.363432     1.0           1  1.599526
Gujarat Titans               1.411904     1.0           1  1.623650
Kings XI Punjab              1.327563     1.0           1  1.612905
Kochi Tuskers Kerala         1.201643     1.0           1  1.517904
Kolkata Knight Riders        1.332622     1.0           1  1.643606
Lucknow Super Giants         1.390741     1.0           1  1.680628
Mumbai Indians               1.341604     1.0           1  1.657214
Pune Warriors                1.168106     1.0           1  1.498203
Punjab Kings                 1.395580     1.0           1  1.720424
Rajasthan Royals             1.324099     1.0           1  1.617359
Rising Pune Supergiant       1.300000     1.0           1  1.561618
Rising Pune Supergiants      1.305696     1.0           1  1.552409
Royal Challengers Bangalore  1.336359     1.0           1  1.638534
Royal Challengers Bengaluru  1.611661     1.0           1  1.853143
Sunrisers Hyderabad          1.330907     1.0           1  1.595941

In [13]:
#task 2:calculate stats for wickets taken by bowlers
wickets_df=df[df["is_wicket"]==1]

wicket_stats={
    "Mean":wickets_df["is_wicket"].mean(),
    "Median":wickets_df["is_wicket"].median(),
    "Mode":wickets_df["is_wicket"].mode()[0],
}
print("\n Wicket statistics:")
print(wicket_stats)

 Wicket statistics:
{'Mean': 1.0, 'Median': 1.0, 'Mode': 1}

In [15]:
batter_stats=df.groupby('batter').agg(
    total_runs=('batsman_runs','sum'),
    times_out=('is_wicket','sum')
).reset_index()
batter_stats

             batter  total_runs  times_out
0    A Ashish Reddy         280         15
1          A Badoni         634         26
2        A Chandila           4          1
3          A Chopra          53          5
4       A Choudhary          25          2
..              ...         ...        ...
668   Yashpal Singh          47          4
669     Younis Khan           3          1
670   Yudhvir Singh          22          4
671    Yuvraj Singh        2754        109
672          Z Khan         117         15

[673 rows x 3 columns]

In [16]:
batter_stats['average']=batter_stats.apply(lambda x:x['total_runs']/x['times_out'] if x['times_out']>0 else 0,axis=1)
batter_stats

             batter  total_runs  times_out    average
0    A Ashish Reddy         280         15  18.666667
1          A Badoni         634         26  24.384615
2        A Chandila           4          1   4.000000
3          A Chopra          53          5  10.600000
4       A Choudhary          25          2  12.500000
..              ...         ...        ...        ...
668   Yashpal Singh          47          4  11.750000
669     Younis Khan           3          1   3.000000
670   Yudhvir Singh          22          4   5.500000
671    Yuvraj Singh        2754        109  25.266055
672          Z Khan         117         15   7.800000

[673 rows x 4 columns]